apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todoapp-monitor
  namespace: todoapp
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: todoapp
  namespaceSelector:
    matchNames:
      - todoapp
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 10s